/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables;


import cn.clubox.quiz.jooq.domain.Keys;
import cn.clubox.quiz.jooq.domain.Quiz;
import cn.clubox.quiz.jooq.domain.tables.records.QuizPricingRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizPricing extends TableImpl<QuizPricingRecord> {

    private static final long serialVersionUID = -1949348547;

    /**
     * The reference instance of <code>quiz.quiz_pricing</code>
     */
    public static final QuizPricing QUIZ_PRICING = new QuizPricing();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuizPricingRecord> getRecordType() {
        return QuizPricingRecord.class;
    }

    /**
     * The column <code>quiz.quiz_pricing.id</code>.
     */
    public final TableField<QuizPricingRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>quiz.quiz_pricing.quiz_id</code>.
     */
    public final TableField<QuizPricingRecord, Integer> QUIZ_ID = createField("quiz_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>quiz.quiz_pricing.price</code>.
     */
    public final TableField<QuizPricingRecord, Integer> PRICE = createField("price", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>quiz.quiz_pricing.status</code>.
     */
    public final TableField<QuizPricingRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.CHAR.length(1).nullable(false), this, "");

    /**
     * The column <code>quiz.quiz_pricing.stored</code>.
     */
    public final TableField<QuizPricingRecord, Timestamp> STORED = createField("stored", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>quiz.quiz_pricing</code> table reference
     */
    public QuizPricing() {
        this("quiz_pricing", null);
    }

    /**
     * Create an aliased <code>quiz.quiz_pricing</code> table reference
     */
    public QuizPricing(String alias) {
        this(alias, QUIZ_PRICING);
    }

    private QuizPricing(String alias, Table<QuizPricingRecord> aliased) {
        this(alias, aliased, null);
    }

    private QuizPricing(String alias, Table<QuizPricingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Quiz.QUIZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<QuizPricingRecord, Integer> getIdentity() {
        return Keys.IDENTITY_QUIZ_PRICING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<QuizPricingRecord> getPrimaryKey() {
        return Keys.KEY_QUIZ_PRICING_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<QuizPricingRecord>> getKeys() {
        return Arrays.<UniqueKey<QuizPricingRecord>>asList(Keys.KEY_QUIZ_PRICING_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<QuizPricingRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<QuizPricingRecord, ?>>asList(Keys.FK_QUIZ_PRICING_QUIZ_QUIZ_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizPricing as(String alias) {
        return new QuizPricing(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuizPricing rename(String name) {
        return new QuizPricing(name, null);
    }
}
