/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables;


import cn.clubox.quiz.jooq.domain.Keys;
import cn.clubox.quiz.jooq.domain.Quiz;
import cn.clubox.quiz.jooq.domain.tables.records.QuizQuestionOptionRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizQuestionOption extends TableImpl<QuizQuestionOptionRecord> {

    private static final long serialVersionUID = -356203918;

    /**
     * The reference instance of <code>quiz.quiz_question_option</code>
     */
    public static final QuizQuestionOption QUIZ_QUESTION_OPTION = new QuizQuestionOption();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuizQuestionOptionRecord> getRecordType() {
        return QuizQuestionOptionRecord.class;
    }

    /**
     * The column <code>quiz.quiz_question_option.id</code>.
     */
    public final TableField<QuizQuestionOptionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>quiz.quiz_question_option.quiz_question_id</code>.
     */
    public final TableField<QuizQuestionOptionRecord, Integer> QUIZ_QUESTION_ID = createField("quiz_question_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>quiz.quiz_question_option.title</code>.
     */
    public final TableField<QuizQuestionOptionRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>quiz.quiz_question_option.stored</code>.
     */
    public final TableField<QuizQuestionOptionRecord, Timestamp> STORED = createField("stored", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>quiz.quiz_question_option.score</code>.
     */
    public final TableField<QuizQuestionOptionRecord, Short> SCORE = createField("score", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>quiz.quiz_question_option.sequence_number</code>.
     */
    public final TableField<QuizQuestionOptionRecord, Short> SEQUENCE_NUMBER = createField("sequence_number", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * Create a <code>quiz.quiz_question_option</code> table reference
     */
    public QuizQuestionOption() {
        this("quiz_question_option", null);
    }

    /**
     * Create an aliased <code>quiz.quiz_question_option</code> table reference
     */
    public QuizQuestionOption(String alias) {
        this(alias, QUIZ_QUESTION_OPTION);
    }

    private QuizQuestionOption(String alias, Table<QuizQuestionOptionRecord> aliased) {
        this(alias, aliased, null);
    }

    private QuizQuestionOption(String alias, Table<QuizQuestionOptionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Quiz.QUIZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<QuizQuestionOptionRecord, Integer> getIdentity() {
        return Keys.IDENTITY_QUIZ_QUESTION_OPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<QuizQuestionOptionRecord> getPrimaryKey() {
        return Keys.KEY_QUIZ_QUESTION_OPTION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<QuizQuestionOptionRecord>> getKeys() {
        return Arrays.<UniqueKey<QuizQuestionOptionRecord>>asList(Keys.KEY_QUIZ_QUESTION_OPTION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<QuizQuestionOptionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<QuizQuestionOptionRecord, ?>>asList(Keys.FK_QUIZ_QUESTION_OPTION_QUIZ_QUESTION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizQuestionOption as(String alias) {
        return new QuizQuestionOption(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuizQuestionOption rename(String name) {
        return new QuizQuestionOption(name, null);
    }
}
