/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.daos;


import cn.clubox.quiz.jooq.domain.tables.QuizTradeNoCounter;
import cn.clubox.quiz.jooq.domain.tables.records.QuizTradeNoCounterRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizTradeNoCounterDao extends DAOImpl<QuizTradeNoCounterRecord, cn.clubox.quiz.jooq.domain.tables.pojos.QuizTradeNoCounter, Integer> {

    /**
     * Create a new QuizTradeNoCounterDao without any configuration
     */
    public QuizTradeNoCounterDao() {
        super(QuizTradeNoCounter.QUIZ_TRADE_NO_COUNTER, cn.clubox.quiz.jooq.domain.tables.pojos.QuizTradeNoCounter.class);
    }

    /**
     * Create a new QuizTradeNoCounterDao with an attached configuration
     */
    public QuizTradeNoCounterDao(Configuration configuration) {
        super(QuizTradeNoCounter.QUIZ_TRADE_NO_COUNTER, cn.clubox.quiz.jooq.domain.tables.pojos.QuizTradeNoCounter.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.clubox.quiz.jooq.domain.tables.pojos.QuizTradeNoCounter object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.QuizTradeNoCounter> fetchById(Integer... values) {
        return fetch(QuizTradeNoCounter.QUIZ_TRADE_NO_COUNTER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.clubox.quiz.jooq.domain.tables.pojos.QuizTradeNoCounter fetchOneById(Integer value) {
        return fetchOne(QuizTradeNoCounter.QUIZ_TRADE_NO_COUNTER.ID, value);
    }

    /**
     * Fetch records that have <code>trade_no IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.QuizTradeNoCounter> fetchByTradeNo(Integer... values) {
        return fetch(QuizTradeNoCounter.QUIZ_TRADE_NO_COUNTER.TRADE_NO, values);
    }
}
