/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.daos;


import cn.clubox.quiz.jooq.domain.tables.QuizEngagement;
import cn.clubox.quiz.jooq.domain.tables.records.QuizEngagementRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizEngagementDao extends DAOImpl<QuizEngagementRecord, cn.clubox.quiz.jooq.domain.tables.pojos.QuizEngagement, Integer> {

    /**
     * Create a new QuizEngagementDao without any configuration
     */
    public QuizEngagementDao() {
        super(QuizEngagement.QUIZ_ENGAGEMENT, cn.clubox.quiz.jooq.domain.tables.pojos.QuizEngagement.class);
    }

    /**
     * Create a new QuizEngagementDao with an attached configuration
     */
    public QuizEngagementDao(Configuration configuration) {
        super(QuizEngagement.QUIZ_ENGAGEMENT, cn.clubox.quiz.jooq.domain.tables.pojos.QuizEngagement.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.clubox.quiz.jooq.domain.tables.pojos.QuizEngagement object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.QuizEngagement> fetchById(Integer... values) {
        return fetch(QuizEngagement.QUIZ_ENGAGEMENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.clubox.quiz.jooq.domain.tables.pojos.QuizEngagement fetchOneById(Integer value) {
        return fetchOne(QuizEngagement.QUIZ_ENGAGEMENT.ID, value);
    }

    /**
     * Fetch records that have <code>quiz_id IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.QuizEngagement> fetchByQuizId(Integer... values) {
        return fetch(QuizEngagement.QUIZ_ENGAGEMENT.QUIZ_ID, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.QuizEngagement> fetchByUserId(Integer... values) {
        return fetch(QuizEngagement.QUIZ_ENGAGEMENT.USER_ID, values);
    }

    /**
     * Fetch records that have <code>duration IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.QuizEngagement> fetchByDuration(String... values) {
        return fetch(QuizEngagement.QUIZ_ENGAGEMENT.DURATION, values);
    }

    /**
     * Fetch records that have <code>stored IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.QuizEngagement> fetchByStored(Timestamp... values) {
        return fetch(QuizEngagement.QUIZ_ENGAGEMENT.STORED, values);
    }
}
