/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.daos;


import cn.clubox.quiz.jooq.domain.tables.UserFederation;
import cn.clubox.quiz.jooq.domain.tables.records.UserFederationRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFederationDao extends DAOImpl<UserFederationRecord, cn.clubox.quiz.jooq.domain.tables.pojos.UserFederation, Integer> {

    /**
     * Create a new UserFederationDao without any configuration
     */
    public UserFederationDao() {
        super(UserFederation.USER_FEDERATION, cn.clubox.quiz.jooq.domain.tables.pojos.UserFederation.class);
    }

    /**
     * Create a new UserFederationDao with an attached configuration
     */
    public UserFederationDao(Configuration configuration) {
        super(UserFederation.USER_FEDERATION, cn.clubox.quiz.jooq.domain.tables.pojos.UserFederation.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.clubox.quiz.jooq.domain.tables.pojos.UserFederation object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.UserFederation> fetchById(Integer... values) {
        return fetch(UserFederation.USER_FEDERATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.clubox.quiz.jooq.domain.tables.pojos.UserFederation fetchOneById(Integer value) {
        return fetchOne(UserFederation.USER_FEDERATION.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.UserFederation> fetchByUserId(Integer... values) {
        return fetch(UserFederation.USER_FEDERATION.USER_ID, values);
    }

    /**
     * Fetch records that have <code>federation_id IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.UserFederation> fetchByFederationId(String... values) {
        return fetch(UserFederation.USER_FEDERATION.FEDERATION_ID, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.UserFederation> fetchByStatus(String... values) {
        return fetch(UserFederation.USER_FEDERATION.STATUS, values);
    }

    /**
     * Fetch records that have <code>stored IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.UserFederation> fetchByStored(Timestamp... values) {
        return fetch(UserFederation.USER_FEDERATION.STORED, values);
    }
}
