/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.daos;


import cn.clubox.quiz.jooq.domain.tables.UserSource;
import cn.clubox.quiz.jooq.domain.tables.records.UserSourceRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSourceDao extends DAOImpl<UserSourceRecord, cn.clubox.quiz.jooq.domain.tables.pojos.UserSource, Integer> {

    /**
     * Create a new UserSourceDao without any configuration
     */
    public UserSourceDao() {
        super(UserSource.USER_SOURCE, cn.clubox.quiz.jooq.domain.tables.pojos.UserSource.class);
    }

    /**
     * Create a new UserSourceDao with an attached configuration
     */
    public UserSourceDao(Configuration configuration) {
        super(UserSource.USER_SOURCE, cn.clubox.quiz.jooq.domain.tables.pojos.UserSource.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.clubox.quiz.jooq.domain.tables.pojos.UserSource object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.UserSource> fetchById(Integer... values) {
        return fetch(UserSource.USER_SOURCE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.clubox.quiz.jooq.domain.tables.pojos.UserSource fetchOneById(Integer value) {
        return fetchOne(UserSource.USER_SOURCE.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.UserSource> fetchByUserId(Integer... values) {
        return fetch(UserSource.USER_SOURCE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>source IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.UserSource> fetchBySource(String... values) {
        return fetch(UserSource.USER_SOURCE.SOURCE, values);
    }

    /**
     * Fetch records that have <code>ip_address IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.UserSource> fetchByIpAddress(String... values) {
        return fetch(UserSource.USER_SOURCE.IP_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>channel IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.UserSource> fetchByChannel(String... values) {
        return fetch(UserSource.USER_SOURCE.CHANNEL, values);
    }

    /**
     * Fetch records that have <code>stored IN (values)</code>
     */
    public List<cn.clubox.quiz.jooq.domain.tables.pojos.UserSource> fetchByStored(Timestamp... values) {
        return fetch(UserSource.USER_SOURCE.STORED, values);
    }
}
