/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.records;


import cn.clubox.quiz.jooq.domain.tables.QuizEngagementResult;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizEngagementResultRecord extends UpdatableRecordImpl<QuizEngagementResultRecord> implements Record5<Integer, Integer, Integer, String, Timestamp> {

    private static final long serialVersionUID = 87936855;

    /**
     * Setter for <code>quiz.quiz_engagement_result.id</code>.
     */
    public QuizEngagementResultRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_engagement_result.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>quiz.quiz_engagement_result.quiz_engagement_id</code>.
     */
    public QuizEngagementResultRecord setQuizEngagementId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_engagement_result.quiz_engagement_id</code>.
     */
    public Integer getQuizEngagementId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>quiz.quiz_engagement_result.score</code>.
     */
    public QuizEngagementResultRecord setScore(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_engagement_result.score</code>.
     */
    public Integer getScore() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>quiz.quiz_engagement_result.result_option</code>.
     */
    public QuizEngagementResultRecord setResultOption(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_engagement_result.result_option</code>.
     */
    public String getResultOption() {
        return (String) get(3);
    }

    /**
     * Setter for <code>quiz.quiz_engagement_result.stored</code>.
     */
    public QuizEngagementResultRecord setStored(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_engagement_result.stored</code>.
     */
    public Timestamp getStored() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return QuizEngagementResult.QUIZ_ENGAGEMENT_RESULT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return QuizEngagementResult.QUIZ_ENGAGEMENT_RESULT.QUIZ_ENGAGEMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return QuizEngagementResult.QUIZ_ENGAGEMENT_RESULT.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return QuizEngagementResult.QUIZ_ENGAGEMENT_RESULT.RESULT_OPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return QuizEngagementResult.QUIZ_ENGAGEMENT_RESULT.STORED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getQuizEngagementId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getResultOption();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getStored();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizEngagementResultRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizEngagementResultRecord value2(Integer value) {
        setQuizEngagementId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizEngagementResultRecord value3(Integer value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizEngagementResultRecord value4(String value) {
        setResultOption(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizEngagementResultRecord value5(Timestamp value) {
        setStored(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizEngagementResultRecord values(Integer value1, Integer value2, Integer value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuizEngagementResultRecord
     */
    public QuizEngagementResultRecord() {
        super(QuizEngagementResult.QUIZ_ENGAGEMENT_RESULT);
    }

    /**
     * Create a detached, initialised QuizEngagementResultRecord
     */
    public QuizEngagementResultRecord(Integer id, Integer quizEngagementId, Integer score, String resultOption, Timestamp stored) {
        super(QuizEngagementResult.QUIZ_ENGAGEMENT_RESULT);

        set(0, id);
        set(1, quizEngagementId);
        set(2, score);
        set(3, resultOption);
        set(4, stored);
    }
}
