/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.records;


import cn.clubox.quiz.jooq.domain.tables.QuizQuestionOption;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizQuestionOptionRecord extends UpdatableRecordImpl<QuizQuestionOptionRecord> implements Record6<Integer, Integer, String, Timestamp, Short, Short> {

    private static final long serialVersionUID = 678177667;

    /**
     * Setter for <code>quiz.quiz_question_option.id</code>.
     */
    public QuizQuestionOptionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_question_option.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>quiz.quiz_question_option.quiz_question_id</code>.
     */
    public QuizQuestionOptionRecord setQuizQuestionId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_question_option.quiz_question_id</code>.
     */
    public Integer getQuizQuestionId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>quiz.quiz_question_option.title</code>.
     */
    public QuizQuestionOptionRecord setTitle(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_question_option.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>quiz.quiz_question_option.stored</code>.
     */
    public QuizQuestionOptionRecord setStored(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_question_option.stored</code>.
     */
    public Timestamp getStored() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>quiz.quiz_question_option.score</code>.
     */
    public QuizQuestionOptionRecord setScore(Short value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_question_option.score</code>.
     */
    public Short getScore() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>quiz.quiz_question_option.sequence_number</code>.
     */
    public QuizQuestionOptionRecord setSequenceNumber(Short value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_question_option.sequence_number</code>.
     */
    public Short getSequenceNumber() {
        return (Short) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, Timestamp, Short, Short> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, Timestamp, Short, Short> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return QuizQuestionOption.QUIZ_QUESTION_OPTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return QuizQuestionOption.QUIZ_QUESTION_OPTION.QUIZ_QUESTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return QuizQuestionOption.QUIZ_QUESTION_OPTION.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return QuizQuestionOption.QUIZ_QUESTION_OPTION.STORED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field5() {
        return QuizQuestionOption.QUIZ_QUESTION_OPTION.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field6() {
        return QuizQuestionOption.QUIZ_QUESTION_OPTION.SEQUENCE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getQuizQuestionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getStored();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value5() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value6() {
        return getSequenceNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizQuestionOptionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizQuestionOptionRecord value2(Integer value) {
        setQuizQuestionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizQuestionOptionRecord value3(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizQuestionOptionRecord value4(Timestamp value) {
        setStored(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizQuestionOptionRecord value5(Short value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizQuestionOptionRecord value6(Short value) {
        setSequenceNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizQuestionOptionRecord values(Integer value1, Integer value2, String value3, Timestamp value4, Short value5, Short value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuizQuestionOptionRecord
     */
    public QuizQuestionOptionRecord() {
        super(QuizQuestionOption.QUIZ_QUESTION_OPTION);
    }

    /**
     * Create a detached, initialised QuizQuestionOptionRecord
     */
    public QuizQuestionOptionRecord(Integer id, Integer quizQuestionId, String title, Timestamp stored, Short score, Short sequenceNumber) {
        super(QuizQuestionOption.QUIZ_QUESTION_OPTION);

        set(0, id);
        set(1, quizQuestionId);
        set(2, title);
        set(3, stored);
        set(4, score);
        set(5, sequenceNumber);
    }
}
