/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.records;


import cn.clubox.quiz.jooq.domain.tables.QuizEngagement;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizEngagementRecord extends UpdatableRecordImpl<QuizEngagementRecord> implements Record5<Integer, Integer, Integer, String, Timestamp> {

    private static final long serialVersionUID = 20794862;

    /**
     * Setter for <code>quiz.quiz_engagement.id</code>.
     */
    public QuizEngagementRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_engagement.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>quiz.quiz_engagement.quiz_id</code>.
     */
    public QuizEngagementRecord setQuizId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_engagement.quiz_id</code>.
     */
    public Integer getQuizId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>quiz.quiz_engagement.user_id</code>.
     */
    public QuizEngagementRecord setUserId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_engagement.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>quiz.quiz_engagement.duration</code>.
     */
    public QuizEngagementRecord setDuration(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_engagement.duration</code>.
     */
    public String getDuration() {
        return (String) get(3);
    }

    /**
     * Setter for <code>quiz.quiz_engagement.stored</code>.
     */
    public QuizEngagementRecord setStored(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>quiz.quiz_engagement.stored</code>.
     */
    public Timestamp getStored() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return QuizEngagement.QUIZ_ENGAGEMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return QuizEngagement.QUIZ_ENGAGEMENT.QUIZ_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return QuizEngagement.QUIZ_ENGAGEMENT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return QuizEngagement.QUIZ_ENGAGEMENT.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return QuizEngagement.QUIZ_ENGAGEMENT.STORED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getQuizId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getStored();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizEngagementRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizEngagementRecord value2(Integer value) {
        setQuizId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizEngagementRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizEngagementRecord value4(String value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizEngagementRecord value5(Timestamp value) {
        setStored(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuizEngagementRecord values(Integer value1, Integer value2, Integer value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuizEngagementRecord
     */
    public QuizEngagementRecord() {
        super(QuizEngagement.QUIZ_ENGAGEMENT);
    }

    /**
     * Create a detached, initialised QuizEngagementRecord
     */
    public QuizEngagementRecord(Integer id, Integer quizId, Integer userId, String duration, Timestamp stored) {
        super(QuizEngagement.QUIZ_ENGAGEMENT);

        set(0, id);
        set(1, quizId);
        set(2, userId);
        set(3, duration);
        set(4, stored);
    }
}
