/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.records;


import cn.clubox.quiz.jooq.domain.tables.UserFederation;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFederationRecord extends UpdatableRecordImpl<UserFederationRecord> implements Record5<Integer, Integer, String, String, Timestamp> {

    private static final long serialVersionUID = -493148031;

    /**
     * Setter for <code>quiz.user_federation.id</code>.
     */
    public UserFederationRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_federation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>quiz.user_federation.user_id</code>.
     */
    public UserFederationRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_federation.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>quiz.user_federation.federation_id</code>.
     */
    public UserFederationRecord setFederationId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_federation.federation_id</code>.
     */
    public String getFederationId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>quiz.user_federation.status</code>.
     */
    public UserFederationRecord setStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_federation.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>quiz.user_federation.stored</code>.
     */
    public UserFederationRecord setStored(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_federation.stored</code>.
     */
    public Timestamp getStored() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserFederation.USER_FEDERATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserFederation.USER_FEDERATION.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserFederation.USER_FEDERATION.FEDERATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserFederation.USER_FEDERATION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return UserFederation.USER_FEDERATION.STORED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFederationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getStored();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserFederationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserFederationRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserFederationRecord value3(String value) {
        setFederationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserFederationRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserFederationRecord value5(Timestamp value) {
        setStored(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserFederationRecord values(Integer value1, Integer value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserFederationRecord
     */
    public UserFederationRecord() {
        super(UserFederation.USER_FEDERATION);
    }

    /**
     * Create a detached, initialised UserFederationRecord
     */
    public UserFederationRecord(Integer id, Integer userId, String federationId, String status, Timestamp stored) {
        super(UserFederation.USER_FEDERATION);

        set(0, id);
        set(1, userId);
        set(2, federationId);
        set(3, status);
        set(4, stored);
    }
}
