/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.records;


import cn.clubox.quiz.jooq.domain.tables.UserPayment;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPaymentRecord extends UpdatableRecordImpl<UserPaymentRecord> implements Record8<Integer, Integer, Integer, BigDecimal, Timestamp, String, String, String> {

    private static final long serialVersionUID = -1088523890;

    /**
     * Setter for <code>quiz.user_payment.id</code>.
     */
    public UserPaymentRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_payment.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>quiz.user_payment.user_id</code>.
     */
    public UserPaymentRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_payment.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>quiz.user_payment.quiz_id</code>.
     */
    public UserPaymentRecord setQuizId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_payment.quiz_id</code>.
     */
    public Integer getQuizId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>quiz.user_payment.amount</code>.
     */
    public UserPaymentRecord setAmount(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_payment.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>quiz.user_payment.stored</code>.
     */
    public UserPaymentRecord setStored(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_payment.stored</code>.
     */
    public Timestamp getStored() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>quiz.user_payment.status</code>.
     */
    public UserPaymentRecord setStatus(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_payment.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>quiz.user_payment.trade_no</code>.
     */
    public UserPaymentRecord setTradeNo(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_payment.trade_no</code>.
     */
    public String getTradeNo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>quiz.user_payment.out_transaction_id</code>.
     */
    public UserPaymentRecord setOutTransactionId(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_payment.out_transaction_id</code>.
     */
    public String getOutTransactionId() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, BigDecimal, Timestamp, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, BigDecimal, Timestamp, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserPayment.USER_PAYMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserPayment.USER_PAYMENT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserPayment.USER_PAYMENT.QUIZ_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return UserPayment.USER_PAYMENT.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return UserPayment.USER_PAYMENT.STORED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return UserPayment.USER_PAYMENT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return UserPayment.USER_PAYMENT.TRADE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return UserPayment.USER_PAYMENT.OUT_TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getQuizId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getStored();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTradeNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getOutTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPaymentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPaymentRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPaymentRecord value3(Integer value) {
        setQuizId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPaymentRecord value4(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPaymentRecord value5(Timestamp value) {
        setStored(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPaymentRecord value6(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPaymentRecord value7(String value) {
        setTradeNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPaymentRecord value8(String value) {
        setOutTransactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPaymentRecord values(Integer value1, Integer value2, Integer value3, BigDecimal value4, Timestamp value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserPaymentRecord
     */
    public UserPaymentRecord() {
        super(UserPayment.USER_PAYMENT);
    }

    /**
     * Create a detached, initialised UserPaymentRecord
     */
    public UserPaymentRecord(Integer id, Integer userId, Integer quizId, BigDecimal amount, Timestamp stored, String status, String tradeNo, String outTransactionId) {
        super(UserPayment.USER_PAYMENT);

        set(0, id);
        set(1, userId);
        set(2, quizId);
        set(3, amount);
        set(4, stored);
        set(5, status);
        set(6, tradeNo);
        set(7, outTransactionId);
    }
}
