/*
 * This file is generated by jOOQ.
*/
package cn.clubox.jooq.domain;


import cn.clubox.jooq.domain.tables.Quiz;
import cn.clubox.jooq.domain.tables.QuizEngagement;
import cn.clubox.jooq.domain.tables.QuizEngagementResult;
import cn.clubox.jooq.domain.tables.QuizPricing;
import cn.clubox.jooq.domain.tables.QuizQuestion;
import cn.clubox.jooq.domain.tables.User;
import cn.clubox.jooq.domain.tables.UserPayment;
import cn.clubox.jooq.domain.tables.UserSource;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in quiz
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>quiz.quiz</code>.
     */
    public static final Quiz QUIZ_ = cn.clubox.jooq.domain.tables.Quiz.QUIZ_;

    /**
     * The table <code>quiz.quiz_engagement</code>.
     */
    public static final QuizEngagement QUIZ_ENGAGEMENT = cn.clubox.jooq.domain.tables.QuizEngagement.QUIZ_ENGAGEMENT;

    /**
     * The table <code>quiz.quiz_engagement_result</code>.
     */
    public static final QuizEngagementResult QUIZ_ENGAGEMENT_RESULT = cn.clubox.jooq.domain.tables.QuizEngagementResult.QUIZ_ENGAGEMENT_RESULT;

    /**
     * The table <code>quiz.quiz_pricing</code>.
     */
    public static final QuizPricing QUIZ_PRICING = cn.clubox.jooq.domain.tables.QuizPricing.QUIZ_PRICING;

    /**
     * The table <code>quiz.quiz_question</code>.
     */
    public static final QuizQuestion QUIZ_QUESTION = cn.clubox.jooq.domain.tables.QuizQuestion.QUIZ_QUESTION;

    /**
     * The table <code>quiz.user</code>.
     */
    public static final User USER = cn.clubox.jooq.domain.tables.User.USER;

    /**
     * The table <code>quiz.user_payment</code>.
     */
    public static final UserPayment USER_PAYMENT = cn.clubox.jooq.domain.tables.UserPayment.USER_PAYMENT;

    /**
     * The table <code>quiz.user_source</code>.
     */
    public static final UserSource USER_SOURCE = cn.clubox.jooq.domain.tables.UserSource.USER_SOURCE;
}
