/*
 * This file is generated by jOOQ.
*/
package cn.clubox.jooq.domain.tables.records;


import cn.clubox.jooq.domain.tables.UserSource;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSourceRecord extends UpdatableRecordImpl<UserSourceRecord> implements Record6<Integer, Integer, String, String, String, Timestamp> {

    private static final long serialVersionUID = 329206155;

    /**
     * Setter for <code>quiz.user_source.id</code>.
     */
    public UserSourceRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_source.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>quiz.user_source.user_id</code>.
     */
    public UserSourceRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_source.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>quiz.user_source.source</code>.
     */
    public UserSourceRecord setSource(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_source.source</code>.
     */
    public String getSource() {
        return (String) get(2);
    }

    /**
     * Setter for <code>quiz.user_source.ip_address</code>.
     */
    public UserSourceRecord setIpAddress(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_source.ip_address</code>.
     */
    public String getIpAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>quiz.user_source.channel</code>.
     */
    public UserSourceRecord setChannel(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_source.channel</code>.
     */
    public String getChannel() {
        return (String) get(4);
    }

    /**
     * Setter for <code>quiz.user_source.stored</code>.
     */
    public UserSourceRecord setStored(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>quiz.user_source.stored</code>.
     */
    public Timestamp getStored() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, String, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, String, String, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserSource.USER_SOURCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserSource.USER_SOURCE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserSource.USER_SOURCE.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserSource.USER_SOURCE.IP_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UserSource.USER_SOURCE.CHANNEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return UserSource.USER_SOURCE.STORED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIpAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getChannel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getStored();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSourceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSourceRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSourceRecord value3(String value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSourceRecord value4(String value) {
        setIpAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSourceRecord value5(String value) {
        setChannel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSourceRecord value6(Timestamp value) {
        setStored(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSourceRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserSourceRecord
     */
    public UserSourceRecord() {
        super(UserSource.USER_SOURCE);
    }

    /**
     * Create a detached, initialised UserSourceRecord
     */
    public UserSourceRecord(Integer id, Integer userId, String source, String ipAddress, String channel, Timestamp stored) {
        super(UserSource.USER_SOURCE);

        set(0, id);
        set(1, userId);
        set(2, source);
        set(3, ipAddress);
        set(4, channel);
        set(5, stored);
    }
}
