/*
 * This file is generated by jOOQ.
*/
package cn.clubox.jooq.domain.tables.daos;


import cn.clubox.jooq.domain.tables.QuizQuestion;
import cn.clubox.jooq.domain.tables.records.QuizQuestionRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizQuestionDao extends DAOImpl<QuizQuestionRecord, cn.clubox.jooq.domain.tables.pojos.QuizQuestion, Integer> {

    /**
     * Create a new QuizQuestionDao without any configuration
     */
    public QuizQuestionDao() {
        super(QuizQuestion.QUIZ_QUESTION, cn.clubox.jooq.domain.tables.pojos.QuizQuestion.class);
    }

    /**
     * Create a new QuizQuestionDao with an attached configuration
     */
    public QuizQuestionDao(Configuration configuration) {
        super(QuizQuestion.QUIZ_QUESTION, cn.clubox.jooq.domain.tables.pojos.QuizQuestion.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.clubox.jooq.domain.tables.pojos.QuizQuestion object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.clubox.jooq.domain.tables.pojos.QuizQuestion> fetchById(Integer... values) {
        return fetch(QuizQuestion.QUIZ_QUESTION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.clubox.jooq.domain.tables.pojos.QuizQuestion fetchOneById(Integer value) {
        return fetchOne(QuizQuestion.QUIZ_QUESTION.ID, value);
    }

    /**
     * Fetch records that have <code>quiz_id IN (values)</code>
     */
    public List<cn.clubox.jooq.domain.tables.pojos.QuizQuestion> fetchByQuizId(Integer... values) {
        return fetch(QuizQuestion.QUIZ_QUESTION.QUIZ_ID, values);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<cn.clubox.jooq.domain.tables.pojos.QuizQuestion> fetchByTitle(String... values) {
        return fetch(QuizQuestion.QUIZ_QUESTION.TITLE, values);
    }

    /**
     * Fetch records that have <code>stored IN (values)</code>
     */
    public List<cn.clubox.jooq.domain.tables.pojos.QuizQuestion> fetchByStored(Timestamp... values) {
        return fetch(QuizQuestion.QUIZ_QUESTION.STORED, values);
    }

    /**
     * Fetch records that have <code>updated IN (values)</code>
     */
    public List<cn.clubox.jooq.domain.tables.pojos.QuizQuestion> fetchByUpdated(Timestamp... values) {
        return fetch(QuizQuestion.QUIZ_QUESTION.UPDATED, values);
    }

    /**
     * Fetch records that have <code>sequence_number IN (values)</code>
     */
    public List<cn.clubox.jooq.domain.tables.pojos.QuizQuestion> fetchBySequenceNumber(Short... values) {
        return fetch(QuizQuestion.QUIZ_QUESTION.SEQUENCE_NUMBER, values);
    }
}
