/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain;


import cn.clubox.quiz.jooq.domain.tables.QuizEngagement;
import cn.clubox.quiz.jooq.domain.tables.QuizEngagementResult;
import cn.clubox.quiz.jooq.domain.tables.QuizPricing;
import cn.clubox.quiz.jooq.domain.tables.QuizQuestion;
import cn.clubox.quiz.jooq.domain.tables.User;
import cn.clubox.quiz.jooq.domain.tables.UserPayment;
import cn.clubox.quiz.jooq.domain.tables.UserSource;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Quiz extends SchemaImpl {

    private static final long serialVersionUID = 468575454;

    /**
     * The reference instance of <code>quiz</code>
     */
    public static final Quiz QUIZ = new Quiz();

    /**
     * The table <code>quiz.quiz</code>.
     */
    public final cn.clubox.quiz.jooq.domain.tables.Quiz QUIZ_ = cn.clubox.quiz.jooq.domain.tables.Quiz.QUIZ_;

    /**
     * The table <code>quiz.quiz_engagement</code>.
     */
    public final QuizEngagement QUIZ_ENGAGEMENT = cn.clubox.quiz.jooq.domain.tables.QuizEngagement.QUIZ_ENGAGEMENT;

    /**
     * The table <code>quiz.quiz_engagement_result</code>.
     */
    public final QuizEngagementResult QUIZ_ENGAGEMENT_RESULT = cn.clubox.quiz.jooq.domain.tables.QuizEngagementResult.QUIZ_ENGAGEMENT_RESULT;

    /**
     * The table <code>quiz.quiz_pricing</code>.
     */
    public final QuizPricing QUIZ_PRICING = cn.clubox.quiz.jooq.domain.tables.QuizPricing.QUIZ_PRICING;

    /**
     * The table <code>quiz.quiz_question</code>.
     */
    public final QuizQuestion QUIZ_QUESTION = cn.clubox.quiz.jooq.domain.tables.QuizQuestion.QUIZ_QUESTION;

    /**
     * The table <code>quiz.user</code>.
     */
    public final User USER = cn.clubox.quiz.jooq.domain.tables.User.USER;

    /**
     * The table <code>quiz.user_payment</code>.
     */
    public final UserPayment USER_PAYMENT = cn.clubox.quiz.jooq.domain.tables.UserPayment.USER_PAYMENT;

    /**
     * The table <code>quiz.user_source</code>.
     */
    public final UserSource USER_SOURCE = cn.clubox.quiz.jooq.domain.tables.UserSource.USER_SOURCE;

    /**
     * No further instances allowed
     */
    private Quiz() {
        super("quiz", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            cn.clubox.quiz.jooq.domain.tables.Quiz.QUIZ_,
            QuizEngagement.QUIZ_ENGAGEMENT,
            QuizEngagementResult.QUIZ_ENGAGEMENT_RESULT,
            QuizPricing.QUIZ_PRICING,
            QuizQuestion.QUIZ_QUESTION,
            User.USER,
            UserPayment.USER_PAYMENT,
            UserSource.USER_SOURCE);
    }
}
