/*
 * This file is generated by jOOQ.
*/
package cn.clubox.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizQuestion implements Serializable {

    private static final long serialVersionUID = -1691758017;

    private Integer   id;
    private Integer   quizId;
    private String    title;
    private Timestamp stored;
    private Timestamp updated;
    private Integer   sequnceNumber;

    public QuizQuestion() {}

    public QuizQuestion(QuizQuestion value) {
        this.id = value.id;
        this.quizId = value.quizId;
        this.title = value.title;
        this.stored = value.stored;
        this.updated = value.updated;
        this.sequnceNumber = value.sequnceNumber;
    }

    public QuizQuestion(
        Integer   id,
        Integer   quizId,
        String    title,
        Timestamp stored,
        Timestamp updated,
        Integer   sequnceNumber
    ) {
        this.id = id;
        this.quizId = quizId;
        this.title = title;
        this.stored = stored;
        this.updated = updated;
        this.sequnceNumber = sequnceNumber;
    }

    public Integer getId() {
        return this.id;
    }

    public QuizQuestion setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getQuizId() {
        return this.quizId;
    }

    public QuizQuestion setQuizId(Integer quizId) {
        this.quizId = quizId;
        return this;
    }

    public String getTitle() {
        return this.title;
    }

    public QuizQuestion setTitle(String title) {
        this.title = title;
        return this;
    }

    public Timestamp getStored() {
        return this.stored;
    }

    public QuizQuestion setStored(Timestamp stored) {
        this.stored = stored;
        return this;
    }

    public Timestamp getUpdated() {
        return this.updated;
    }

    public QuizQuestion setUpdated(Timestamp updated) {
        this.updated = updated;
        return this;
    }

    public Integer getSequnceNumber() {
        return this.sequnceNumber;
    }

    public QuizQuestion setSequnceNumber(Integer sequnceNumber) {
        this.sequnceNumber = sequnceNumber;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QuizQuestion (");

        sb.append(id);
        sb.append(", ").append(quizId);
        sb.append(", ").append(title);
        sb.append(", ").append(stored);
        sb.append(", ").append(updated);
        sb.append(", ").append(sequnceNumber);

        sb.append(")");
        return sb.toString();
    }
}
