/*
 * This file is generated by jOOQ.
*/
package cn.clubox.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Quiz implements Serializable {

    private static final long serialVersionUID = 582596908;

    private Integer   id;
    private String    title;
    private String    description;
    private String    status;
    private Timestamp stored;
    private String    quizType;

    public Quiz() {}

    public Quiz(Quiz value) {
        this.id = value.id;
        this.title = value.title;
        this.description = value.description;
        this.status = value.status;
        this.stored = value.stored;
        this.quizType = value.quizType;
    }

    public Quiz(
        Integer   id,
        String    title,
        String    description,
        String    status,
        Timestamp stored,
        String    quizType
    ) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.status = status;
        this.stored = stored;
        this.quizType = quizType;
    }

    public Integer getId() {
        return this.id;
    }

    public Quiz setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getTitle() {
        return this.title;
    }

    public Quiz setTitle(String title) {
        this.title = title;
        return this;
    }

    public String getDescription() {
        return this.description;
    }

    public Quiz setDescription(String description) {
        this.description = description;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public Quiz setStatus(String status) {
        this.status = status;
        return this;
    }

    public Timestamp getStored() {
        return this.stored;
    }

    public Quiz setStored(Timestamp stored) {
        this.stored = stored;
        return this;
    }

    public String getQuizType() {
        return this.quizType;
    }

    public Quiz setQuizType(String quizType) {
        this.quizType = quizType;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Quiz (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(status);
        sb.append(", ").append(stored);
        sb.append(", ").append(quizType);

        sb.append(")");
        return sb.toString();
    }
}
