/*
 * This file is generated by jOOQ.
*/
package cn.clubox.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1771559959;

    private Integer   id;
    private String    name;
    private String    portraitSrc;
    private Timestamp stored;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.portraitSrc = value.portraitSrc;
        this.stored = value.stored;
    }

    public User(
        Integer   id,
        String    name,
        String    portraitSrc,
        Timestamp stored
    ) {
        this.id = id;
        this.name = name;
        this.portraitSrc = portraitSrc;
        this.stored = stored;
    }

    public Integer getId() {
        return this.id;
    }

    public User setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public User setName(String name) {
        this.name = name;
        return this;
    }

    public String getPortraitSrc() {
        return this.portraitSrc;
    }

    public User setPortraitSrc(String portraitSrc) {
        this.portraitSrc = portraitSrc;
        return this;
    }

    public Timestamp getStored() {
        return this.stored;
    }

    public User setStored(Timestamp stored) {
        this.stored = stored;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(portraitSrc);
        sb.append(", ").append(stored);

        sb.append(")");
        return sb.toString();
    }
}
