/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Quiz implements Serializable {

    private static final long serialVersionUID = 1654111300;

    private Integer   id;
    private String    title;
    private String    description;
    private String    status;
    private Timestamp stored;
    private String    quizType;
    private String    logoSrc;
    private String    name;
    private String    quizSrc;

    public Quiz() {}

    public Quiz(Quiz value) {
        this.id = value.id;
        this.title = value.title;
        this.description = value.description;
        this.status = value.status;
        this.stored = value.stored;
        this.quizType = value.quizType;
        this.logoSrc = value.logoSrc;
        this.name = value.name;
        this.quizSrc = value.quizSrc;
    }

    public Quiz(
        Integer   id,
        String    title,
        String    description,
        String    status,
        Timestamp stored,
        String    quizType,
        String    logoSrc,
        String    name,
        String    quizSrc
    ) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.status = status;
        this.stored = stored;
        this.quizType = quizType;
        this.logoSrc = logoSrc;
        this.name = name;
        this.quizSrc = quizSrc;
    }

    public Integer getId() {
        return this.id;
    }

    public Quiz setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getTitle() {
        return this.title;
    }

    public Quiz setTitle(String title) {
        this.title = title;
        return this;
    }

    public String getDescription() {
        return this.description;
    }

    public Quiz setDescription(String description) {
        this.description = description;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public Quiz setStatus(String status) {
        this.status = status;
        return this;
    }

    public Timestamp getStored() {
        return this.stored;
    }

    public Quiz setStored(Timestamp stored) {
        this.stored = stored;
        return this;
    }

    public String getQuizType() {
        return this.quizType;
    }

    public Quiz setQuizType(String quizType) {
        this.quizType = quizType;
        return this;
    }

    public String getLogoSrc() {
        return this.logoSrc;
    }

    public Quiz setLogoSrc(String logoSrc) {
        this.logoSrc = logoSrc;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Quiz setName(String name) {
        this.name = name;
        return this;
    }

    public String getQuizSrc() {
        return this.quizSrc;
    }

    public Quiz setQuizSrc(String quizSrc) {
        this.quizSrc = quizSrc;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Quiz (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(status);
        sb.append(", ").append(stored);
        sb.append(", ").append(quizType);
        sb.append(", ").append(logoSrc);
        sb.append(", ").append(name);
        sb.append(", ").append(quizSrc);

        sb.append(")");
        return sb.toString();
    }
}
