/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizTradeNoCounter implements Serializable {

    private static final long serialVersionUID = 995426411;

    private Integer id;
    private Integer counter;

    public QuizTradeNoCounter() {}

    public QuizTradeNoCounter(QuizTradeNoCounter value) {
        this.id = value.id;
        this.counter = value.counter;
    }

    public QuizTradeNoCounter(
        Integer id,
        Integer counter
    ) {
        this.id = id;
        this.counter = counter;
    }

    public Integer getId() {
        return this.id;
    }

    public QuizTradeNoCounter setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getCounter() {
        return this.counter;
    }

    public QuizTradeNoCounter setCounter(Integer counter) {
        this.counter = counter;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QuizTradeNoCounter (");

        sb.append(id);
        sb.append(", ").append(counter);

        sb.append(")");
        return sb.toString();
    }
}
