/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizEngagement implements Serializable {

    private static final long serialVersionUID = 561970322;

    private Integer   id;
    private Integer   quizId;
    private Integer   userId;
    private String    duration;
    private Timestamp stored;
    private String    status;
    private Timestamp updated;

    public QuizEngagement() {}

    public QuizEngagement(QuizEngagement value) {
        this.id = value.id;
        this.quizId = value.quizId;
        this.userId = value.userId;
        this.duration = value.duration;
        this.stored = value.stored;
        this.status = value.status;
        this.updated = value.updated;
    }

    public QuizEngagement(
        Integer   id,
        Integer   quizId,
        Integer   userId,
        String    duration,
        Timestamp stored,
        String    status,
        Timestamp updated
    ) {
        this.id = id;
        this.quizId = quizId;
        this.userId = userId;
        this.duration = duration;
        this.stored = stored;
        this.status = status;
        this.updated = updated;
    }

    public Integer getId() {
        return this.id;
    }

    public QuizEngagement setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getQuizId() {
        return this.quizId;
    }

    public QuizEngagement setQuizId(Integer quizId) {
        this.quizId = quizId;
        return this;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public QuizEngagement setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    public String getDuration() {
        return this.duration;
    }

    public QuizEngagement setDuration(String duration) {
        this.duration = duration;
        return this;
    }

    public Timestamp getStored() {
        return this.stored;
    }

    public QuizEngagement setStored(Timestamp stored) {
        this.stored = stored;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public QuizEngagement setStatus(String status) {
        this.status = status;
        return this;
    }

    public Timestamp getUpdated() {
        return this.updated;
    }

    public QuizEngagement setUpdated(Timestamp updated) {
        this.updated = updated;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QuizEngagement (");

        sb.append(id);
        sb.append(", ").append(quizId);
        sb.append(", ").append(userId);
        sb.append(", ").append(duration);
        sb.append(", ").append(stored);
        sb.append(", ").append(status);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
