/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizEngagementResult implements Serializable {

    private static final long serialVersionUID = 1076814968;

    private Integer   id;
    private Integer   quizEngagementId;
    private Short     score;
    private String    resultOption;
    private Timestamp stored;
    private Short     questionId;

    public QuizEngagementResult() {}

    public QuizEngagementResult(QuizEngagementResult value) {
        this.id = value.id;
        this.quizEngagementId = value.quizEngagementId;
        this.score = value.score;
        this.resultOption = value.resultOption;
        this.stored = value.stored;
        this.questionId = value.questionId;
    }

    public QuizEngagementResult(
        Integer   id,
        Integer   quizEngagementId,
        Short     score,
        String    resultOption,
        Timestamp stored,
        Short     questionId
    ) {
        this.id = id;
        this.quizEngagementId = quizEngagementId;
        this.score = score;
        this.resultOption = resultOption;
        this.stored = stored;
        this.questionId = questionId;
    }

    public Integer getId() {
        return this.id;
    }

    public QuizEngagementResult setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getQuizEngagementId() {
        return this.quizEngagementId;
    }

    public QuizEngagementResult setQuizEngagementId(Integer quizEngagementId) {
        this.quizEngagementId = quizEngagementId;
        return this;
    }

    public Short getScore() {
        return this.score;
    }

    public QuizEngagementResult setScore(Short score) {
        this.score = score;
        return this;
    }

    public String getResultOption() {
        return this.resultOption;
    }

    public QuizEngagementResult setResultOption(String resultOption) {
        this.resultOption = resultOption;
        return this;
    }

    public Timestamp getStored() {
        return this.stored;
    }

    public QuizEngagementResult setStored(Timestamp stored) {
        this.stored = stored;
        return this;
    }

    public Short getQuestionId() {
        return this.questionId;
    }

    public QuizEngagementResult setQuestionId(Short questionId) {
        this.questionId = questionId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QuizEngagementResult (");

        sb.append(id);
        sb.append(", ").append(quizEngagementId);
        sb.append(", ").append(score);
        sb.append(", ").append(resultOption);
        sb.append(", ").append(stored);
        sb.append(", ").append(questionId);

        sb.append(")");
        return sb.toString();
    }
}
