/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSource implements Serializable {

    private static final long serialVersionUID = -714560703;

    private Integer   id;
    private Integer   userId;
    private String    source;
    private String    ipAddress;
    private String    channel;
    private Timestamp stored;

    public UserSource() {}

    public UserSource(UserSource value) {
        this.id = value.id;
        this.userId = value.userId;
        this.source = value.source;
        this.ipAddress = value.ipAddress;
        this.channel = value.channel;
        this.stored = value.stored;
    }

    public UserSource(
        Integer   id,
        Integer   userId,
        String    source,
        String    ipAddress,
        String    channel,
        Timestamp stored
    ) {
        this.id = id;
        this.userId = userId;
        this.source = source;
        this.ipAddress = ipAddress;
        this.channel = channel;
        this.stored = stored;
    }

    public Integer getId() {
        return this.id;
    }

    public UserSource setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public UserSource setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    public String getSource() {
        return this.source;
    }

    public UserSource setSource(String source) {
        this.source = source;
        return this;
    }

    public String getIpAddress() {
        return this.ipAddress;
    }

    public UserSource setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
        return this;
    }

    public String getChannel() {
        return this.channel;
    }

    public UserSource setChannel(String channel) {
        this.channel = channel;
        return this;
    }

    public Timestamp getStored() {
        return this.stored;
    }

    public UserSource setStored(Timestamp stored) {
        this.stored = stored;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserSource (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(source);
        sb.append(", ").append(ipAddress);
        sb.append(", ").append(channel);
        sb.append(", ").append(stored);

        sb.append(")");
        return sb.toString();
    }
}
