/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -210338526;

    private Integer   id;
    private String    name;
    private String    portraitSrc;
    private Timestamp stored;
    private String    password;
    private String    nickname;
    private String    status;
    private Timestamp updated;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.portraitSrc = value.portraitSrc;
        this.stored = value.stored;
        this.password = value.password;
        this.nickname = value.nickname;
        this.status = value.status;
        this.updated = value.updated;
    }

    public User(
        Integer   id,
        String    name,
        String    portraitSrc,
        Timestamp stored,
        String    password,
        String    nickname,
        String    status,
        Timestamp updated
    ) {
        this.id = id;
        this.name = name;
        this.portraitSrc = portraitSrc;
        this.stored = stored;
        this.password = password;
        this.nickname = nickname;
        this.status = status;
        this.updated = updated;
    }

    public Integer getId() {
        return this.id;
    }

    public User setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public User setName(String name) {
        this.name = name;
        return this;
    }

    public String getPortraitSrc() {
        return this.portraitSrc;
    }

    public User setPortraitSrc(String portraitSrc) {
        this.portraitSrc = portraitSrc;
        return this;
    }

    public Timestamp getStored() {
        return this.stored;
    }

    public User setStored(Timestamp stored) {
        this.stored = stored;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public User setPassword(String password) {
        this.password = password;
        return this;
    }

    public String getNickname() {
        return this.nickname;
    }

    public User setNickname(String nickname) {
        this.nickname = nickname;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public User setStatus(String status) {
        this.status = status;
        return this;
    }

    public Timestamp getUpdated() {
        return this.updated;
    }

    public User setUpdated(Timestamp updated) {
        this.updated = updated;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(portraitSrc);
        sb.append(", ").append(stored);
        sb.append(", ").append(password);
        sb.append(", ").append(nickname);
        sb.append(", ").append(status);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
