/*
 * This file is generated by jOOQ.
*/
package cn.clubox.quiz.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFederation implements Serializable {

    private static final long serialVersionUID = -18972351;

    private Integer   id;
    private Integer   userId;
    private String    federationId;
    private String    status;
    private Timestamp stored;

    public UserFederation() {}

    public UserFederation(UserFederation value) {
        this.id = value.id;
        this.userId = value.userId;
        this.federationId = value.federationId;
        this.status = value.status;
        this.stored = value.stored;
    }

    public UserFederation(
        Integer   id,
        Integer   userId,
        String    federationId,
        String    status,
        Timestamp stored
    ) {
        this.id = id;
        this.userId = userId;
        this.federationId = federationId;
        this.status = status;
        this.stored = stored;
    }

    public Integer getId() {
        return this.id;
    }

    public UserFederation setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public UserFederation setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    public String getFederationId() {
        return this.federationId;
    }

    public UserFederation setFederationId(String federationId) {
        this.federationId = federationId;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public UserFederation setStatus(String status) {
        this.status = status;
        return this;
    }

    public Timestamp getStored() {
        return this.stored;
    }

    public UserFederation setStored(Timestamp stored) {
        this.stored = stored;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserFederation (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(federationId);
        sb.append(", ").append(status);
        sb.append(", ").append(stored);

        sb.append(")");
        return sb.toString();
    }
}
